# Generated by Django 6.0.3 on 2026-03-04 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_todo_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="is_active",
        ),
    ]
